# As of development, bun is v1.2.9
FROM oven/bun:1.2-alpine AS build

# Set the working directory
WORKDIR /app

# Install dependencies
COPY package.json tsconfig.json ./
RUN bun install --production

# Copy server code
COPY server/. .

EXPOSE 8443

CMD [ "bun", "run", "server.ts" ]